language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep_history: true
  on:
    branch: master
