language: node_js
node_js:
  - 16 # 推荐使用LTS版本

install:
  - npm install

script:
  - npm run docs:build

deploy:
  provider: pages
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN # 在Travis设置的环境变量
  keep_history: true
  target_branch: gh-pages
  on:
    branch: main

cache:
  directories:
    - node_modules
