name: 部署文档

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 安装Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          
      - name: 安装依赖
        run: npm ci
        
      - name: 构建
        run: npm run docs:build
        
      - name: 部署到GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vuepress/dist
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository-name: guanyuhao/guanyuhao.github.io
          branch: main
          clean: true